name: tests
on: push
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
      - name: installation
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: make install
      - name: check linter status
        run: make lint
      - name: run test with coverage
        run: make test-coverage
      - name: codeclimate coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
